### ISSUE TITLE
Sav sziget érc generator fejlesztés.

### ISSUE THREAD

**Issue by baawoof** [TheOld-Crafters/Minecraft-servers#4440]
Lapis Lazuli érc hozzáadása a Gyémánt generatorhoz. 15% eséllyel, úgy mint a sima Lazurit generátorban. Minden más érc megtalálható benne csak ez nem ami fura.

**Comment by andris155** [comment]
Jelenleg így néz ki:
```
    blocks:
      STONE: 20
      COAL_ORE: 5
      IRON_ORE: 35
      GOLD_ORE: 10
      REDSTONE_ORE: 20
      EMERALD_ORE: 5
      DIAMOND_ORE: 5
```
A számok százalékos értékek és 100%-ot kell kiadniuk. Mennyi legyen a lapis érc és miből kerüljön levonásra a %?
