### ISSUE TITLE
mcMMO képességek használata közben fizetés növelés a levonás helyett

### ISSUE THREAD

**Issue by UDPSendToFailed** [TheOld-Crafters/Minecraft-servers#4482]
Jelenleg a Jobs az eredeti fizetés 20%-át adja mcMMO képességek használatakor, ezt fel lehetne vinni 180-200%-ra. Néhány másodpercig működnek a képességek, tehát sokat nem lehet belőlük farmolni, de kezdőknek segítene valamennyit.

**Comment by Sanszi** [comment]
Vagy lehetne alapbeállítás 100%.

**Comment by UDPSendToFailed** [comment]
Legyen a kettő között, 150. Az a max 8-10 másodperces skill 5 percenként nem fog túl sokat adni pluszban.

**Comment by skrisz0101** [comment]
Nem sok, de legalább érzik a törődést

**Comment by andris155** [comment]
Hol kell ezt átállítani?

**Comment by UDPSendToFailed** [comment]
```
  McMMO:
    # Players will get part of money from cutting trees with treefeller ability enabled.
    # 0.2 means 20% of original price
    TreeFellerMultiplier: 0.2
    # Players will get part of money from braking blocks with gigaDrill ability enabled.
    # 0.2 means 20% of original price
    gigaDrillMultiplier: 0.2
    # Players will get part of money from braking blocks with super breaker ability enabled.
    # 0.2 means 20% of original price
    superBreakerMultiplier: 0.2
```
